engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
      rulesets: ".codeclimate.phpmd.xml"
  duplication:
    enabled: true
    config:
      languages:
        - php

ratings:
  paths:
    - src/**/*.php

exclude_paths:
  - tests/**/*
  - vendor/**/*
  - build/**/*
