language: php

php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

addons:
  code_climate:
    repo_token: 17b808b7927d3459ad9c780083bea52528879b3ebabc6e68e1d3f98dd6c42920

cache:
  directories:
    - vendor

install:
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test_reporter
